### ISSUE TITLE
What is necessary for these tests to run properly locally?

### ISSUE THREAD

**Issue by SDGGiesbrecht** [realm/jazzy-integration-specs#24]
My local results still do not match those of the continuous integration.

If I do the following, the miscellaneous Objective‐C, Moya, Alamofire and Siesta tests fail en masse. (Realm, Realm Objective‐C, and miscellaneous Swift tests succeed.)
```shell
git clone https://github.com/realm/jazzy
cd jazzy
sudo xcode-select -switch [/path/to/xcode/7.3.1]
bundle install
bundle exec rake bootstrap
bundle exec rake spec
```
So far, I’ve been able to manually sort out which failures will only be local and avoid commiting those generated specs, but there has to be a better way. Does anyone have any ideas what is wrong with my environment?

**Comment by segiddins** [comment]
Can you share a gist of the failures you're seeing locally?

**Comment by jpsim** [comment]
That's how I run the specs without issues, so very curious to see how this is failing for you.

If you're having networking issues, or if GitHub is down, the Moya spec will fail since it installs with CocoaPods.

**Comment by SDGGiesbrecht** [comment]
I pasted the entire Terminal session [here](https://gist.github.com/SDGGiesbrecht/d1c50da11e542e25941504bb97ab1bb8).

This time around Alamofire succeeded and Moya only had problems with `index.html`. Siesta and Objective‐C were still a mess.

**Comment by jpsim** [comment]
Are you sure you're running these tests with Xcode 7.3.1?

The error message from your gist would seem to indicate otherwise:

> ROOT/lib/jazzy/sourcekitten.rb:140:in `run_sourcekitten': Unable to find an Xcode with swift version 2.2. (RuntimeError)

**Comment by SDGGiesbrecht** [comment]
I switched to it at [this line](https://gist.github.com/SDGGiesbrecht/d1c50da11e542e25941504bb97ab1bb8#file-jazzy-spec-output-L31).

“Get Info” on `Xcode for Jazzy/Xcode.app` says “Version 7.3.1”.

This question is out of date anyway.

**Comment by jpsim** [comment]
Ah, actually then the reason [xcinvoke](https://github.com/segiddins/xcinvoke) might not be finding that Xcode version could be that Spotlight hasn't had the chance to, or just won't, index that location.

**Comment by jpsim** [comment]
Although it'd be nice if xcinvoke could not just check Spotlight, but also the location specified by `xcode-select`.

**Comment by SDGGiesbrecht** [comment]
That would be it. Spotlight is turned off. I never use it.

**Comment by segiddins** [comment]
A PR to xcinvoke with that change would be :rocket:
